import Head from "next/head";
import Features from "@/components/Features";
import About from "@/components/About";
import Card from "@/components/Card";
import Cta from "@/components/Cta";
import Testimonial from "@/components/Testimonial";
import HeroInnerPages from "@/components/HeroInnerPages";
import ContactCom from "@/components/ContactCom";

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroInnerPages title="Contact" />
        <ContactCom />

        <div>Go to Pepoform.ai and get the form code</div>

        <Features />
        <About />
        <Card />
        <Testimonial />
        <Cta />
      </main>
    </>
  );
}
