import Head from "next/head";
import Features from "@/components/Features";
import About from "@/components/About";
import Card from "@/components/Card";
import Cta from "@/components/Cta";
import Testimonial from "@/components/Testimonial";
import HeroInnerPages from "@/components/HeroInnerPages";
import TeamCom from "@/components/TeamCom";

export default function Team() {
  return (
    <>
      <Head>
        <title>Team</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroInnerPages title="Our Team" />
        <TeamCom />
        <Features />
        <About />
        <Card />
        <Testimonial />
        <Cta />
      </main>
    </>
  );
}
