import Head from "next/head";
import Navbar from "@/components/Navbar";
import Features from "@/components/Features";
import About from "@/components/About";
import Card from "@/components/Card";
import Cta from "@/components/Cta";
import Testimonial from "@/components/Testimonial";
import { Footer } from "@/components/Footer";
import HeroInnerPages from "@/components/HeroInnerPages";
import AboutCom from "@/components/AboutCom";

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroInnerPages title="About" />
        <AboutCom />
        <Features />
        <About />
        <Card />
        <Testimonial />
        <Cta />
      </main>
    </>
  );
}
